services:
  web:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/mentors?schema=public'
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mentors
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
